FTP Quick Reminder:
 If you are using a browser to FTP:
   1. Your Home directory listing will appear in your browser window.
   2. You can drag-and-drop files into the browser window from any PC
      window.

 Note: if your ftp client sets the initial directory:
   1. The old initial (home) directory was "/mywebpages".
   2. The new initial (home) directory is just "/"
   3. We have upgraded the servers.  Please reconfigure
      your software!

